name: Build and Deploy Code

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}            # Host of your server
          username: ${{ secrets.USERNAME }}    # SSH user
          key: ${{ secrets.SSH_KEY }}          # Private key
          passphrase: ${{ secrets.SSH_PASSPHRASE }} # Passphrase for the private key
          script: |
            cd /src/
            git pull
            systemctl restart api.service
